### ISSUE TITLE
Script won't save in Chrome or Firefox

### ISSUE THREAD

**Issue by sheaC42** [onrik/django-webshell#6] opened 2017-02-02 11:23 UTC
It seems there is a hidden field that has the `required` attribute and so Chrome and Firefox think the form is not completely filled in and will not send the POST request to save it.

I fixed this issue in my own Django project by adding the line 
```python
ScriptAdmin.form.use_required_attribute = False
```
 in my admin.py so that is potentially a fix for this issue though maybe there is a better solution.  Adding this line still makes the `Name` and `Source` fields required so this doesn't change any functionality.  

![screen shot 2017-02-02 at 12 15 07](https://cloud.githubusercontent.com/assets/22611639/22547387/ac43a5a2-e941-11e6-8f72-c50c87161e03.png)

![screen shot 2017-02-02 at 12 14 22](https://cloud.githubusercontent.com/assets/22611639/22547391/ae6eff84-e941-11e6-8582-17f6b4ada50e.png)

**Comment by onrik** [comment] 2017-02-03 13:36
I can't reproduce. Please provide your browser and django versions.

**Comment by sheaC42** [comment] 2017-02-03 13:54
Django version 1.10.3
Chrome version 55.0.2883.95 (64-bit)
Firefox version 51.0.1 (64-bit)

**Comment by onrik** [comment] 2017-02-04 08:07
Fixed in v0.2.3

**Closed as completed by onrik** 2017-02-04 08:07 UTC

**Comment by xcriptus** [comment] 2017-06-01 08:20
Bonjour,
I've just installed webshell (cool!) and I've the same problem. But it is just realized that this is because pypi has v0.2.2 and v0.2.3  has not been pushed there.

**Comment by onrik** [comment] 2017-06-02 07:09
@escribis It's really some problem with 0.2.3 in pypi. Please try to 0.2.4
